# Loki Configuration v2.8.x
# High-availability log aggregation system for HotGigs platform

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 4MB
  grpc_server_max_send_msg_size: 4MB

common:
  path_prefix: /loki
  storage:
    s3:
      endpoint: s3.amazonaws.com
      bucketnames: hotgigs-logs
      region: us-east-1
      s3forcepathstyle: false
      insecure: false
      sse_encryption: true
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 30d
  max_query_length: 721h
  max_query_parallelism: 32
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_streams_per_user: 10000
  max_line_size: 256kb
  max_entries_limit_per_query: 5000
  max_cache_freshness_per_query: 1m

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d
  poll_interval: 12h
  creation_grace_period: 24h

ruler:
  storage:
    s3:
      bucketnames: hotgigs-logs-rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: memberlist
  enable_api: true

distributor:
  ring:
    kvstore:
      store: memberlist
  ingestion_rate_strategy: global
  ingestion_rate_limit_mb: 10
  ingestion_burst_size_mb: 20

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_target_size: 1572864
  chunk_encoding: snappy
  max_transfer_retries: 3

querier:
  engine:
    timeout: 3m
    max_look_back_period: 30d
  query_ingesters_within: 3h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: s3

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_mb: 1024
        validity: 24h

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  downstream_url: http://querier:3100

frontend_worker:
  frontend_address: frontend:9095
  grpc_client_config:
    max_send_msg_size: 4MB
    max_recv_msg_size: 4MB

memberlist:
  join_members:
    - loki-memberlist
  bind_port: 7946
  abort_if_cluster_join_fails: false
  max_join_retries: 10
  max_join_backoff: 1m